=== fitzpatrick/cow-ac/cow-ac-suite/build/testuserdir/agileclient/DATA/local/TMS/Tables/Platform.dtd
<!ELEMENT Platform (body)>

	<!ELEMENT body (entry)*>
	<!ELEMENT entry (type, description)>

	<!ELEMENT type (#PCDATA)>
	<!ELEMENT description (#PCDATA)>

=== fitzpatrick/cow-ac/cow-ac-suite/build/testuserdir/agileclient/DATA/local/TMS/Tables/Platform.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE body SYSTEM "Platform.dtd">
<body>
<entry>
<type>AA</type>
<description>AUXILIARY TYPE SHIP, GENERAL</description>
</entry>
<entry>
<type>AAA</type>
<description>ANTIAIRCRAFT GUN</description>
</entry>
<entry>
<type>AAAH</type>
<description>AAA HEAVY (100MM OR LARGER)</description>
</entry>
<entry>
<type>AAAL</type>
<description>AAA LIGHT (20-57MM)</description>
</entry>
<entry>
<type>AAALA</type>
<description>AAA LIGHT AUTO (UNDER 20MM)</description>
</entry>
<entry>
<type>AAAMDM</type>
<description>AAA MEDIUM (58-99MM)</description>
</entry>
<entry>
<type>AAASP</type>
<description>AAA SELF-PROPELLED</description>
</entry>
<entry>
<type>AAATOW</type>
<description>AAA TOWED</description>
</entry>
<entry>
<type>AAM</type>
<description>ROCKET/MISSILE AIR-TO-AIR</description>
</entry>
<entry>
<type>AB</type>
<description>DEPOT SHIP/TENDER</description>
</entry>
<entry>
<type>ABU</type>
<description>BOUY TENDER</description>
</entry>
<entry>
<type>ABUD</type>
<description>BOUY TENDER, HEAVY LIFT</description>
</entry>
<entry>
<type>ACFT</type>
<description>AIRCRAFT</description>
</entry>
<entry>
<type>ACM</type>
<description>AUXILIARY MINE WARFARE SUPPORT SHIP</description>
</entry>
<entry>
<type>AD</type>
<description>DESTROYER TENDER</description>
</entry>
<entry>
<type>ADA</type>
<description>AIR DEFENSE ARTILLERY</description>
</entry>
<entry>
<type>ADAH</type>
<description>ADA HEAVY (100MM OR LARGER)</description>
</entry>
<entry>
<type>ADAL</type>
<description>ADA LIGHT (20-57MM)</description>
</entry>
<entry>
<type>ADAMDM</type>
<description>ADA MEDIUM (58-99MM)</description>
</entry>
<entry>
<type>ADAMSL</type>
<description>ADA MISSILE</description>
</entry>
<entry>
<type>ADAPOS</type>
<description>POSITION AREA</description>
</entry>
<entry>
<type>ADG</type>
<description>DEPERMING SHIP</description>
</entry>
<entry>
<type>ADHQ</type>
<description>AIR DEFENSE HEADQUARTERS</description>
</entry>
<entry>
<type>ADM</type>
<description>ROCKET/MISSILE AIR DEFENSE</description>
</entry>
<entry>
<type>AE</type>
<description>AMMUNITION SHIP</description>
</entry>
<entry>
<type>AEL</type>
<description>AMMUNITION SHIP, SMALL</description>
</entry>
<entry>
<type>AEM</type>
<description>MISSILE SUPPORT SHIP</description>
</entry>
<entry>
<type>AET</type>
<description>AMMUNITION TRANSPORT</description>
</entry>
<entry>
<type>AETL</type>
<description>AMMUNITION TRANSPORT, SMALL</description>
</entry>
<entry>
<type>AF</type>
<description>STORES SHIP</description>
</entry>
<entry>
<type>AFBASE</type>
<description>AIR FORCE BASE</description>
</entry>
<entry>
<type>AFDB</type>
<description>AUXILIARY FLOATING DRYDOCK, LARGE</description>
</entry>
<entry>
<type>AFDL</type>
<description>AUXILIARY FLOATING DRYDOCK, SMALL</description>
</entry>
<entry>
<type>AFDM</type>
<description>AUXILIARY FLOATING DRYDOCK, MEDIUM</description>
</entry>
<entry>
<type>AFL</type>
<description>STORES SHIP, SMALL</description>
</entry>
<entry>
<type>AFLD</type>
<description>AIRFIELD</description>
</entry>
<entry>
<type>AFS</type>
<description>STORES SHIP, COMBAT</description>
</entry>
<entry>
<type>AFT</type>
<description>STORES, SHIP, TRANSPORT</description>
</entry>
<entry>
<type>AG</type>
<description>MISCELLANEOUS AUXILIARY</description>
</entry>
<entry>
<type>AGB</type>
<description>ICEBREAKER</description>
</entry>
<entry>
<type>AGBL</type>
<description>ICEBREAKER, SMALL</description>
</entry>
<entry>
<type>AGBN</type>
<description>ICEBREAKER, NUCLEAR POWERED</description>
</entry>
<entry>
<type>AGCL</type>
<description>COMMUNICATIONS SHIP, SMALL</description>
</entry>
<entry>
<type>AGDS</type>
<description>DEEP SUBMERGENCE SUPPORT SHIP</description>
</entry>
<entry>
<type>AGE</type>
<description>RESEARCH SHIP</description>
</entry>
<entry>
<type>AGEH</type>
<description>RESEARCH SHIP, HYDROFOIL</description>
</entry>
<entry>
<type>AGENT</type>
<description>AGENT</description>
</entry>
<entry>
<type>AGF</type>
<description>AUXILIARY FLAG OR COMMAND SHIP</description>
</entry>
<entry>
<type>AGFF</type>
<description>RESEARCH SHIP, FRIGATE</description>
</entry>
<entry>
<type>AGH</type>
<description>INSTRUMENTATION SHIP, HYDROACOUSTIC RANGE </description>
</entry>
<entry>
<type>AGI</type>
<description>INTELLIGENCE COLLECTOR</description>
</entry>
<entry>
<type>AGM</type>
<description>MISSILE RANGE INSTRUMENTATION SHIP</description>
</entry>
<entry>
<type>AGMS</type>
<description>SUPPORT SHIP, MISSILE RANGE </description>
</entry>
<entry>
<type>AGOB</type>
<description>OCEANOGRAPHIC RESEARCH SHIP, POLAR</description>
</entry>
<entry>
<type>AGOR</type>
<description>OCEANOGRAPHIC RESEARCH SHIP</description>
</entry>
<entry>
<type>AGOS</type>
<description>OCEAN SURVEILLANCE SHIP</description>
</entry>
<entry>
<type>AGP</type>
<description>PATROL CRAFT TENDER</description>
</entry>
<entry>
<type>AGR</type>
<description>RADAR PICKET SHIP, UNARMED</description>
</entry>
<entry>
<type>AGS</type>
<description>SURVEY SHIP</description>
</entry>
<entry>
<type>AGSA</type>
<description>SURVEYING SHIP, POLAR</description>
</entry>
<entry>
<type>AGSC</type>
<description>SURVEY SHIP, COASTAL</description>
</entry>
<entry>
<type>AGSL</type>
<description>LAUNCHING SHIP, SATELLITE</description>
</entry>
<entry>
<type>AGSS</type>
<description>AUXILIARY RESEARCH SUBMARINE</description>
</entry>
<entry>
<type>AGT</type>
<description>SERVICE SHIP, TARGET</description>
</entry>
<entry>
<type>AGTT</type>
<description>SERVICE SHIP, TORPEDO/TARGET </description>
</entry>
<entry>
<type>AH</type>
<description>HOSPITAL SHIP</description>
</entry>
<entry>
<type>AHDBHD</type>
<description>AIRHEAD/BRIDGEHEAD</description>
</entry>
<entry>
<type>AIRTWR</type>
<description>AIRFIELD OPERATIONS TOWER</description>
</entry>
<entry>
<type>AK</type>
<description>CARGO SHIP, NAVAL</description>
</entry>
<entry>
<type>AKL</type>
<description>CARGO SHIP, LIGHT, NAVAL</description>
</entry>
<entry>
<type>AKR</type>
<description>CARGO SHIP, RO/RO, NAVAL</description>
</entry>
<entry>
<type>AKS</type>
<description>STORES SHIP, ISSUE, NAVAL</description>
</entry>
<entry>
<type>AKV</type>
<description>AIRCRAFT FERRY/CARGO SHIP</description>
</entry>
<entry>
<type>ALOGHQ</type>
<description>AIR LOGISTICS HEADQUARTERS</description>
</entry>
<entry>
<type>ALS</type>
<description>LIGHT SHIP</description>
</entry>
<entry>
<type>AMBL</type>
<description>AMBULANCE</description>
</entry>
<entry>
<type>AMMODP</type>
<description>AMMUNITION DUMP</description>
</entry>
<entry>
<type>AMPHTK</type>
<description>TANK AMPHIBIOUS</description>
</entry>
<entry>
<type>AMPHVH</type>
<description>AMPHIBIOUS VEHICLE</description>
</entry>
<entry>
<type>AN</type>
<description>NET TENDER</description>
</entry>
<entry>
<type>ANL</type>
<description>CABLE/NET LAYING SHIP</description>
</entry>
<entry>
<type>ANT</type>
<description>ANTENNA</description>
</entry>
<entry>
<type>AO</type>
<description>OILER/TANKER, GENERAL</description>
</entry>
<entry>
<type>AOBLST</type>
<description>AIR-OBSTRUCTION LIGHTING</description>
</entry>
<entry>
<type>AOE</type>
<description>COMBAT SUPPORT SHIP, FAST</description>
</entry>
<entry>
<type>AOG</type>
<description>GASOLINE TANKER</description>
</entry>
<entry>
<type>AOL</type>
<description>OILER, SMALL, NAVAL</description>
</entry>
<entry>
<type>AOR</type>
<description>OILER, REPLENISHMENT</description>
</entry>
<entry>
<type>AORL</type>
<description>OILER, REPLENISHMENT, SMALL, NAVAL</description>
</entry>
<entry>
<type>AOS</type>
<description>SPECIAL LIQUID SHIP</description>
</entry>
<entry>
<type>AOSR</type>
<description>RADIOLOGICAL LIQIUID SHIP</description>
</entry>
<entry>
<type>AOT</type>
<description>OILER, TRANSPORT</description>
</entry>
<entry>
<type>AOTL</type>
<description>OILER, TRANSPORT, SMALL</description>
</entry>
<entry>
<type>AP</type>
<description>PERSONNEL TRANSPORT</description>
</entry>
<entry>
<type>APB</type>
<description>BARRACKS SHIP</description>
</entry>
<entry>
<type>APC</type>
<description>ARMORED PERSONNEL CARRIER</description>
</entry>
<entry>
<type>APCR</type>
<description>PRIMARY CASUALTY RECEIVING SHIP</description>
</entry>
<entry>
<type>APCT</type>
<description>CASUALTY TRANSPORT SHIP</description>
</entry>
<entry>
<type>APERS</type>
<description>ROCKET/MISSILE, ANTIPERSONNEL</description>
</entry>
<entry>
<type>APL</type>
<description>BARRACKS CRAFT</description>
</entry>
<entry>
<type>AQ</type>
<description>CRUISE/RAIDER, ARMED, MERCHANT</description>
</entry>
<entry>
<type>AR</type>
<description>REPAIR SHIP</description>
</entry>
<entry>
<type>ARB</type>
<description>REPAIR SHIP, BATTLE DAMAGE </description>
</entry>
<entry>
<type>ARBASE</type>
<description>ARMY BASE</description>
</entry>
<entry>
<type>ARC</type>
<description>CABLE SHIP</description>
</entry>
<entry>
<type>ARD</type>
<description>AUXILIARY REPAIR DOCK</description>
</entry>
<entry>
<type>ARDM</type>
<description>DRYDOCK, AUXILIARY, REPAIR, MEDIUM</description>
</entry>
<entry>
<type>ARH</type>
<description>REPAIR SHIP, HEAVY HULL </description>
</entry>
<entry>
<type>ARL</type>
<description>REPAIR SHIP, SMALL</description>
</entry>
<entry>
<type>ARM</type>
<description>ANTIRADIATION MISSILE WARNING</description>
</entry>
<entry>
<type>ARMOR</type>
<description>COMBAT ARMORED VEHICLE</description>
</entry>
<entry>
<type>ARR</type>
<description>REPAIR SHIP, RADIOLOGICAL</description>
</entry>
<entry>
<type>ARS</type>
<description>SALVAGE SHIP</description>
</entry>
<entry>
<type>ARSD</type>
<description>SALVAGE SHIP, LIFTING</description>
</entry>
<entry>
<type>ARSPVH</type>
<description>ARMORED VEHICLE</description>
</entry>
<entry>
<type>ARTPOS</type>
<description>ARTILLERY POSTION AREA</description>
</entry>
<entry>
<type>ARTY</type>
<description>ARTILLERY</description>
</entry>
<entry>
<type>ARTYH</type>
<description>ARTILLERY HEAVY (161-210MM)</description>
</entry>
<entry>
<type>ARTYL</type>
